HRMSPROJECT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings

import hrms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrms.urls', namespace = 'hrms')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path
from . import views
app_name = 'hrms'
urlpatterns = [

# Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),

    
    path('profile/update/<int:pk>', views.Employee_individual_Update.as_view(), name='employee_individual_update'),

 path('casting/update/<int:pk>', views.Employee_individual_Update_casting.as_view(), name='employee_individual_update_casting'),


    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),


    
    path('dashboard/employee/<int:pk>/newarrangeement/', views.Employee_New_Arrangement.as_view(), name='employee_new_arrangement'),
    path('dashboard/employee/<int:pk>/pastarrangeement/', views.Employee_Past_Arrangement.as_view(), name='employee_past_arrangement'),
 path('dashboard/employee/<int:pk>/updatearrangeement/', views.Employee_Update_Arrangement.as_view(), name='employee_update_arrangement'),


    path('dashboard/employee/<int:pk>/new_coupon_pdf/', views.Employee_New_CouponPdf.as_view(), name='employee_new_coupon_pdf'),
    path('dashboard/employee/<int:pk>/allcouponpdf/', views.Employee_All_Coupon_Pdf.as_view(), name='all_employee_coupon_pdf'),

    path('dashboard/employee/allcouponpdf/',views.Employee_CouponPdf.as_view(),name='individual_all_employee_coupon_pdf'),
#Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

#Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

#Recruitment

    path("recruitment/",views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/",views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

#Payroll
    path("employee/pay/",views.Pay.as_view(), name="payroll"),

# CUSTOMER
    path('dashboard/customer/all/', views.Customer_All.as_view(), name='cust_all'),
    path('dashboard/customer/add/', views.Customer_New.as_view(), name='cust_new'),
    path('dashboard/customer/<int:pk>/update/', views.Customer_Update.as_view(), name='cust_update'),
    path('dashboard/customer/<int:pk>/view/', views.Customer_View.as_view(), name='cust_view'),


    # expenses
    path('dashboard/expenses/all/', views.Expenses_All.as_view(), name='expenses_all'),
    path('dashboard/expense/add/', views.Expenses_New.as_view(), name='expenses_new'),
    # path('dashboard/customer/<int:pk>/update/', views.Customer_Update.as_view(), name='cust_update'),

    path('total_expense', views.getFilteredExpenseDate, name='get_filtered_expense_date'),
    # total_expense


#EMPLOYEE ADVANCE
    path('employee_advance/', views.Employee_Advance, name='employee_advance'),



    path('employee_checkin/', views.Employee_CheckIn, name='employee_checkin'),




    # path('employee_advance/<int:pk>', views.Employee_Advance, name='employee_advance_view'),



    path('work_arrangeement/', views.Employee_All_Arrangement.as_view(), name='work_arrangeement_view'),
    path('employee_salary/', views.Employee_Salary.as_view(), name='employee_salary_view'),
    
    path('chat/<str:pk>', views.room, name='chatroom'),
    path('getMessages/<str:employee_id>/', views.getMessages, name='get_spec_messages'),
    path('send', views.send, name='send'),

    # INDIVIDUAL EMPLOYEE
    path('chat-spec/employer', views.individual_room, name='chat_employer'),
    path('getindividualMessages/employer', views.getSpecMessages, name='get_mes_employer'),
    path('send/employer', views.send, name='send'),

    path('update_paid', views.updatepaid, name='updatepaid'),
   

    
]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

hrms/views.py
from django.shortcuts import render,redirect, resolve_url,reverse, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .models  import (
    Employee, Department,Kin,
     Attendance, Leave, Recruitment,
     Customer,ConcreteCasting,Expenses,EmployeeCouponPdf,EmployeeChat)
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, CreateView,View,DetailView,TemplateView,ListView,UpdateView,DeleteView
from .forms import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q,Sum
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .time_filter import gettime
import json

# Create your views here.
class Index(TemplateView):
   template_name = 'hrms/home/home.html'

#   Authentication
class Register (CreateView):
    model = get_user_model()
    form_class  = RegistrationForm
    template_name = 'hrms/registrations/register.html'
    success_url = reverse_lazy('hrms:login')
    
class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/login.html'

    def get_success_url(self):
        url = resolve_url('hrms:dashboard')
        if self.request.user.role==1:
            url = resolve_url('hrms:dashboard')
        else:
            url = resolve_url('hrms:work_arrangeement_view')
        return url

class Logout_View(View):

    def get(self,request):
        logout(self.request)
        return redirect ('hrms:login',permanent=True)
    
    
 # Main Board   
class Dashboard(LoginRequiredMixin,ListView):
    template_name = 'hrms/dashboard/index.html'
    login_url = 'hrms:login'
    model = get_user_model()
    context_object_name = 'qset'            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.filter(role=1).count()
        context['workers'] = Employee.objects.order_by('-id')
        print(context['workers'])
        return context

# Employee's Controller
class Employee_New(LoginRequiredMixin,CreateView):
    model = Employee  
    form_class = EmployeeForm2  
    template_name = 'hrms/employee/create.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'
    
    success_url = reverse_lazy('hrms:employee_all')

    def form_valid(self, form):
        self.object = form.save()
        new_user = form.instance

        empl = self.model(mobile= form.cleaned_data['mobile'], emergency = form.cleaned_data['emergency'],gender=form.cleaned_data['gender'],department=form.cleaned_data['department'],language=form.cleaned_data['language'],nuban=form.cleaned_data['nuban'],bank=form.cleaned_data['bank'],salary =form.cleaned_data['salary'],user = new_user)
        empl.save()
        print(self.object)
        return HttpResponseRedirect(self.get_success_url())
    
# Employee's Controller

class Employee_Past_Arrangement(LoginRequiredMixin,DetailView):
    queryset = ConcreteCasting.objects.all()
    template_name = 'hrms/employee/single_pages/past_arrangement.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.kwargs['pk'] )
            query = ConcreteCasting.objects.filter(employee=self.kwargs['pk'] )
            context["concretecasting"] = query

            queryset = Employee.objects.get(user=self.kwargs['pk'])
            print(queryset)
            context['employee'] = queryset

            # print(c)
            return context
        except ObjectDoesNotExist:
            return context
class Employee_All_Arrangement(LoginRequiredMixin,ListView):
    queryset = ConcreteCasting.objects.all()
    template_name = 'hrms/pages/employee/work_arrangement.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.request.user.id)
            print()
            query = ConcreteCasting.objects.filter(employee=Employee.objects.get(user=self.request.user.id))
            print(query)
            context["concretecasting"] = query

            queryset = Employee.objects.get(user=self.request.user.id)
            print(queryset)
            print('*************************')
            
            context['employee'] = queryset

            # print(c)

            print('*************************')
            # CHECK IF ALREADY CHECKED IN
            # context["today"] = timezone.localdate()
            print(Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) )
            pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) 
            context['present'] = pstaff
            print(pstaff)
            return context
        except ObjectDoesNotExist:
            return context
class Employee_Salary(LoginRequiredMixin,ListView):
    queryset = EmployeeAdvancePayment.objects.all()
    template_name = 'hrms/pages/employee/my_salary.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.request.user.id)
            print()
            get_past_month_dates = gettime(0)
            query = EmployeeAdvancePayment.objects.filter(user=self.request.user.id,date_paid__range=[get_past_month_dates['first_day'], get_past_month_dates['last_day']])
            print(query)
            context["advancepayment"] = query

            # GET TOTAL DEDUCTIONS
            query2 = query.aggregate(Sum('amount'))
            context['advanceamount'] = query2['amount__sum']
            print(query2)
            queryset = Employee.objects.get(user=self.request.user.id)
            # print(queryset)
            context['employee'] = queryset
            pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) 
            context['present'] = pstaff
           

            # print(c)
            return context
        except ObjectDoesNotExist:
            return context




class Employee_CouponPdf(LoginRequiredMixin,ListView):
    queryset = EmployeeCouponPdf.objects.all()
    template_name = 'hrms/pages/employee/my_coupons.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.request.user.id)
            print()
            # get_past_month_dates = gettime(0)
            query = EmployeeCouponPdf.objects.filter(user=self.request.user.id)
            print(query)
            context["allcouponpdf"] = query
            pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) 
            context['present'] = pstaff

            queryset = Employee.objects.get(user=self.request.user.id)
            context['employee'] = queryset
           

            return context
        except ObjectDoesNotExist:
            return context         
class Employee_New_Arrangement(LoginRequiredMixin,CreateView):
    model = ConcreteCasting  
    form_class = EmployeeCasting  
    template_name = 'hrms/employee/single_pages/new_arrangement.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'
    # context_object_name = 'employee'
    
    success_url = reverse_lazy('hrms:employee_all') 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print('*********************************')
            print(self.kwargs['pk'])
            queryset = Employee.objects.get(id=self.kwargs['pk'])
            context['employee'] = queryset
            return context
        except ObjectDoesNotExist:
            return context

    def form_valid(self, form):
        # form.instance.owner_id = 2
        print(form.instance.employee)
        self.object = form.save()
        new_arrangement = form.instance
        
        new_arrangement.employee_id =self.kwargs['pk'] 
        new_arrangement.save()
    
        print(self.object)



        return HttpResponseRedirect(self.get_success_url())


class Employee_Update_Arrangement(LoginRequiredMixin,UpdateView):
    model = ConcreteCasting  
    form_class = EmployeeCasting  
    template_name = 'hrms/employee/single_pages/edit_past_arrangement.html'
    login_url = 'hrms:login'
    # redirect_field_name = 'redirect:'

    # model = Employee
    # template_name = 'hrms/employee/edit.html'
    # form_class = EmployeeForm
    # login_url = 'hrms:login'
    context_object_name = 'employee'
    
    success_url = reverse_lazy('hrms:employee_all') 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print('*********************************')
            print(self.kwargs['pk'])
            queryset = Employee.objects.get(id=self.kwargs['pk'])

hrms/templates/hrms/expenses/create.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} New Expense | HRIS {% endblock title %}

{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-12 grid-margin">
                    <div class="card">
                        <div class="card-body">
                           <h4 class="text-center text-primary"><i class="fa fa-plus">&emsp; New Expense </i></h4><hr>
                                <form enctype="multipart/form-data" action="{% url 'hrms:expenses_new' %}" class="form-group" method="POST">
                                    {% csrf_token %}
                                    <small class="mb-5">** All Fields are required</small>
                                        {{form.as_p}}
                                    <div class="text-center mt-3">
                                        <button class="btn btn-outline-success"><i class="mdi mdi-file-document"></i>Save</button></button>
                                        
                                    </div>
                                </form>
                        
                                           
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

hrms/templates/hrms/expenses/index.html
{% extends 'hrms/layout.html' %}
{% load static %}
{% block title %} Business Expenses | HRIS {% endblock title %}
{% block content %}

    <div class="main-panel">
        <div class="content-wrapper">
            <div class="row">
                <div class="col-lg-8 col-md-8 grid-margin">
                    <div class="card">
                      <div class="card-body">
                        <h4 class="card-title">All Business Expenses<a href="{% url 'hrms:expenses_new' %}" class="btn btn-sm btn-success mb-3 float-right">Add New +</a></h4>
                          
                        <div class="table-responsive">
                          <table class="table table-bordered">
                            <thead>
                              <tr>
                                <th>
                                    id
                                  </th>
                                <th>
                                  Price
                                </th>
                           
                                <th>
                                    Description
                                </th>
                                <th>
                                date
                                </th> 
                                                   
                              </tr>
                            </thead>
                            <tbody>
                            {% for expense in expenses  %}
                              <tr>
                                 
                                <td>
                                    {{expense.id}}
                                  </td>
                                <td>
                                  {{expense.price}}
                                </td>
                             
                                <td>
                                 {{expense.description}}
                                </td>
                
                                <td>
                                  {{expense.date_created}}
                                 </td>
                                
                              
                                <td>
                                
                                  <div class="btn-group dropdown">
                                    <button type="button" class="btn btn-success dropdown-toggle btn-rounded btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                     <i class="fa fa-cog "></i> Manage
                                    </button>
                                    <div class="dropdown-menu">
                                      <a class="dropdown-item" href="{% url 'hrms:cust_view' pk=expense.pk %}">
                                        <i class="fa fa-eye text-success fa-fw"></i>View</a>
                                      <a class="dropdown-item" href="{% url 'hrms:cust_update' pk=expense.pk %}">
                                        <i class="fa fa-edit text-info fa-fw"></i>Edit</a>
                                      <div class="dropdown-divider"></div> 
                                    </div>
                                  </div>                  
                                </td>
                              </tr>
                              {% endfor %}
                            </tbody>
                          </table>
                
                          {% if is_paginated %}
                            <nav aria-label="Page navigation example" class='mt-4'>
                              <ul class="pagination">
                              {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{page_obj.previous_page_number}}">Previous</a></li>
                              {% else %}
                
                                <li class="page-item disabled"><span class='page-link '>Previous</span></li>
                              {% endif %}
                                <li class="disabled"> <span class='page-link'> Page {{page_obj.number}} of {{page_obj.paginator.num_pages}} </span></li>
                              {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">Next</a></li>
                              {% else %}
                                <li class="page-item disabled"><span class='page-link '>Next</span></li> 
                              {% endif %}                        
                              </ul>
                          </nav>
                          {% endif %}
                      
                        </div>
                      </div>
                    </div>
                  </div>


                <div class="col-lg-4 col-md-4 grid-margin">
                    <div class="card">
                        <div class="card-body">
                          <h4 class="card-title">All Business Expenses</h4>
                            
                          <div class="table-responsive"> 
                              
                            <div style="display:flex;flex-direction:row">

                                <p>Select Month: </p>
                                <select name="" id="no_of_months"class="no_of_months">
                                    
                                    <option value=0>Past 1 months</option>
                                    <option value=-3>Past 3 months</option>
                                    <option value=-6>Past 6 months</option>
                                    
                                </select>
                            </div>

                            <p>Result: <span id="price_sum">{{price.price__sum}}</span></p>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    {% endblock %}