HRMSPROJECT/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static #this is needed for file and image upload
from django.conf import settings

import hrms

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hrms.urls', namespace = 'hrms')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hrms/urls.py
from django.urls import path
from . import views
app_name = 'hrms'
urlpatterns = [

# Authentication Routes
    path('', views.Index.as_view(), name='index'),
    path('register/', views.Register.as_view(), name='reg'),
    path('login/', views.Login_View.as_view(), name='login'),
    path('logout/', views.Logout_View.as_view(), name='logout'),
    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),

# Employee Routes
    path('dashboard/employee/', views.Employee_All.as_view(), name='employee_all'),
    path('dashboard/employee/new/', views.Employee_New.as_view(), name='employee_new'),
    path('dashboard/employee/<int:pk>/view/', views.Employee_View.as_view(), name='employee_view'),
    path('dashboard/employee/<int:pk>/update/', views.Employee_Update.as_view(), name='employee_update'),

    
    path('profile/update/<int:pk>', views.Employee_individual_Update.as_view(), name='employee_individual_update'),

 path('casting/update/<int:pk>', views.Employee_individual_Update_casting.as_view(), name='employee_individual_update_casting'),


    path('dashboard/employee/<int:pk>/delete/', views.Employee_Delete.as_view(), name='employee_delete'),
    path('dashboard/employee/<int:id>/kin/add/', views.Employee_Kin_Add.as_view(), name='kin_add'),
    path('dashboard/employee/<int:id>/kin/<int:pk>/update/', views.Employee_Kin_Update.as_view(), name='kin_update'),


    
    path('dashboard/employee/<int:pk>/newarrangeement/', views.Employee_New_Arrangement.as_view(), name='employee_new_arrangement'),
    path('dashboard/employee/<int:pk>/pastarrangeement/', views.Employee_Past_Arrangement.as_view(), name='employee_past_arrangement'),
 path('dashboard/employee/<int:pk>/updatearrangeement/', views.Employee_Update_Arrangement.as_view(), name='employee_update_arrangement'),


    path('dashboard/employee/<int:pk>/new_coupon_pdf/', views.Employee_New_CouponPdf.as_view(), name='employee_new_coupon_pdf'),
    path('dashboard/employee/<int:pk>/allcouponpdf/', views.Employee_All_Coupon_Pdf.as_view(), name='all_employee_coupon_pdf'),

    path('dashboard/employee/allcouponpdf/',views.Employee_CouponPdf.as_view(),name='individual_all_employee_coupon_pdf'),
#Department Routes
    path('dashboard/department/<int:pk>/', views.Department_Detail.as_view(), name='dept_detail'),
    path('dashboard/department/add/', views.Department_New.as_view(), name='dept_new'),
    path('dashboard/department/<int:pk>/update/', views.Department_Update.as_view(), name='dept_update'),

#Attendance Routes
    path('dashboard/attendance/in/', views.Attendance_New.as_view(), name='attendance_new'),
    path('dashboard/attendance/<int:pk>/out/', views.Attendance_Out.as_view(), name='attendance_out'),

#Leave Routes

    path("dashboard/leave/new/", views.LeaveNew.as_view(), name="leave_new"),

#Recruitment

    path("recruitment/",views.RecruitmentNew.as_view(), name="recruitment"),
    path("recruitment/all/",views.RecruitmentAll.as_view(), name="recruitmentall"),
    path("recruitment/<int:pk>/delete/", views.RecruitmentDelete.as_view(), name="recruitmentdelete"),

#Payroll
    path("employee/pay/",views.Pay.as_view(), name="payroll"),

# CUSTOMER
    path('dashboard/customer/all/', views.Customer_All.as_view(), name='cust_all'),
    path('dashboard/customer/add/', views.Customer_New.as_view(), name='cust_new'),
    path('dashboard/customer/<int:pk>/update/', views.Customer_Update.as_view(), name='cust_update'),
    path('dashboard/customer/<int:pk>/view/', views.Customer_View.as_view(), name='cust_view'),


    # expenses
    path('dashboard/expenses/all/', views.Expenses_All.as_view(), name='expenses_all'),
    path('dashboard/expense/add/', views.Expenses_New.as_view(), name='expenses_new'),
    # path('dashboard/customer/<int:pk>/update/', views.Customer_Update.as_view(), name='cust_update'),

    path('total_expense', views.getFilteredExpenseDate, name='get_filtered_expense_date'),
    # total_expense


#EMPLOYEE ADVANCE
    path('employee_advance/', views.Employee_Advance, name='employee_advance'),



    path('employee_checkin/', views.Employee_CheckIn, name='employee_checkin'),




    # path('employee_advance/<int:pk>', views.Employee_Advance, name='employee_advance_view'),



    path('work_arrangeement/', views.Employee_All_Arrangement.as_view(), name='work_arrangeement_view'),
    path('employee_salary/', views.Employee_Salary.as_view(), name='employee_salary_view'),
    
    path('chat/<str:pk>', views.room, name='chatroom'),
    path('getMessages/<str:employee_id>/', views.getMessages, name='get_spec_messages'),
    path('send', views.send, name='send'),

    # INDIVIDUAL EMPLOYEE
    path('chat-spec/employer', views.individual_room, name='chat_employer'),
    path('getindividualMessages/employer', views.getSpecMessages, name='get_mes_employer'),
    path('send/employer', views.send, name='send'),

    path('update_paid', views.updatepaid, name='updatepaid'),
   

    
]

web_project/web_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

hrms/views.py
from django.shortcuts import render,redirect, resolve_url,reverse, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth import get_user_model
from .models  import (
    Employee, Department,Kin,
     Attendance, Leave, Recruitment,
     Customer,ConcreteCasting,Expenses,EmployeeCouponPdf,EmployeeChat)
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView, CreateView,View,DetailView,TemplateView,ListView,UpdateView,DeleteView
from .forms import *
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q,Sum
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse

from .time_filter import gettime
import json

# Create your views here.
class Index(TemplateView):
   template_name = 'hrms/home/home.html'

#   Authentication
class Register (CreateView):
    model = get_user_model()
    form_class  = RegistrationForm
    template_name = 'hrms/registrations/register.html'
    success_url = reverse_lazy('hrms:login')
    
class Login_View(LoginView):
    model = get_user_model()
    form_class = LoginForm
    template_name = 'hrms/registrations/login.html'

    def get_success_url(self):
        url = resolve_url('hrms:dashboard')
        if self.request.user.role==1:
            url = resolve_url('hrms:dashboard')
        else:
            url = resolve_url('hrms:work_arrangeement_view')
        return url

class Logout_View(View):

    def get(self,request):
        logout(self.request)
        return redirect ('hrms:login',permanent=True)
    
    
 # Main Board   
class Dashboard(LoginRequiredMixin,ListView):
    template_name = 'hrms/dashboard/index.html'
    login_url = 'hrms:login'
    model = get_user_model()
    context_object_name = 'qset'            
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs) 
        context['emp_total'] = Employee.objects.all().count()
        context['dept_total'] = Department.objects.all().count()
        context['admin_count'] = get_user_model().objects.filter(role=1).count()
        context['workers'] = Employee.objects.order_by('-id')
        print(context['workers'])
        return context

# Employee's Controller
class Employee_New(LoginRequiredMixin,CreateView):
    model = Employee  
    form_class = EmployeeForm2  
    template_name = 'hrms/employee/create.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'
    
    success_url = reverse_lazy('hrms:employee_all')

    def form_valid(self, form):
        self.object = form.save()
        new_user = form.instance

        empl = self.model(mobile= form.cleaned_data['mobile'], emergency = form.cleaned_data['emergency'],gender=form.cleaned_data['gender'],department=form.cleaned_data['department'],language=form.cleaned_data['language'],nuban=form.cleaned_data['nuban'],bank=form.cleaned_data['bank'],salary =form.cleaned_data['salary'],user = new_user)
        empl.save()
        print(self.object)
        return HttpResponseRedirect(self.get_success_url())
    
# Employee's Controller

class Employee_Past_Arrangement(LoginRequiredMixin,DetailView):
    queryset = ConcreteCasting.objects.all()
    template_name = 'hrms/employee/single_pages/past_arrangement.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.kwargs['pk'] )
            query = ConcreteCasting.objects.filter(employee=self.kwargs['pk'] )
            context["concretecasting"] = query

            queryset = Employee.objects.get(user=self.kwargs['pk'])
            print(queryset)
            context['employee'] = queryset

            # print(c)
            return context
        except ObjectDoesNotExist:
            return context
class Employee_All_Arrangement(LoginRequiredMixin,ListView):
    queryset = ConcreteCasting.objects.all()
    template_name = 'hrms/pages/employee/work_arrangement.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.request.user.id)
            print()
            query = ConcreteCasting.objects.filter(employee=Employee.objects.get(user=self.request.user.id))
            print(query)
            context["concretecasting"] = query

            queryset = Employee.objects.get(user=self.request.user.id)
            print(queryset)
            print('*************************')
            
            context['employee'] = queryset

            # print(c)

            print('*************************')
            # CHECK IF ALREADY CHECKED IN
            # context["today"] = timezone.localdate()
            print(Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) )
            pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) 
            context['present'] = pstaff
            print(pstaff)
            return context
        except ObjectDoesNotExist:
            return context
class Employee_Salary(LoginRequiredMixin,ListView):
    queryset = EmployeeAdvancePayment.objects.all()
    template_name = 'hrms/pages/employee/my_salary.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.request.user.id)
            print()
            get_past_month_dates = gettime(0)
            query = EmployeeAdvancePayment.objects.filter(user=self.request.user.id,date_paid__range=[get_past_month_dates['first_day'], get_past_month_dates['last_day']])
            print(query)
            context["advancepayment"] = query

            # GET TOTAL DEDUCTIONS
            query2 = query.aggregate(Sum('amount'))
            context['advanceamount'] = query2['amount__sum']
            print(query2)
            queryset = Employee.objects.get(user=self.request.user.id)
            # print(queryset)
            context['employee'] = queryset
            pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) 
            context['present'] = pstaff
           

            # print(c)
            return context
        except ObjectDoesNotExist:
            return context




class Employee_CouponPdf(LoginRequiredMixin,ListView):
    queryset = EmployeeCouponPdf.objects.all()
    template_name = 'hrms/pages/employee/my_coupons.html'
    context_object_name = 'employee'
    login_url = 'hrms:login'
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print(self.request.user.id)
            print()
            # get_past_month_dates = gettime(0)
            query = EmployeeCouponPdf.objects.filter(user=self.request.user.id)
            print(query)
            context["allcouponpdf"] = query
            pstaff = Attendance.objects.filter(Q(status='PRESENT') & Q (date=timezone.localdate()),staff=Employee.objects.get(user=self.request.user.id)) 
            context['present'] = pstaff

            queryset = Employee.objects.get(user=self.request.user.id)
            context['employee'] = queryset
           

            return context
        except ObjectDoesNotExist:
            return context         
class Employee_New_Arrangement(LoginRequiredMixin,CreateView):
    model = ConcreteCasting  
    form_class = EmployeeCasting  
    template_name = 'hrms/employee/single_pages/new_arrangement.html'
    login_url = 'hrms:login'
    redirect_field_name = 'redirect:'
    # context_object_name = 'employee'
    
    success_url = reverse_lazy('hrms:employee_all') 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print('*********************************')
            print(self.kwargs['pk'])
            queryset = Employee.objects.get(id=self.kwargs['pk'])
            context['employee'] = queryset
            return context
        except ObjectDoesNotExist:
            return context

    def form_valid(self, form):
        # form.instance.owner_id = 2
        print(form.instance.employee)
        self.object = form.save()
        new_arrangement = form.instance
        
        new_arrangement.employee_id =self.kwargs['pk'] 
        new_arrangement.save()
    
        print(self.object)



        return HttpResponseRedirect(self.get_success_url())


class Employee_Update_Arrangement(LoginRequiredMixin,UpdateView):
    model = ConcreteCasting  
    form_class = EmployeeCasting  
    template_name = 'hrms/employee/single_pages/edit_past_arrangement.html'
    login_url = 'hrms:login'
    # redirect_field_name = 'redirect:'

    # model = Employee
    # template_name = 'hrms/employee/edit.html'
    # form_class = EmployeeForm
    # login_url = 'hrms:login'
    context_object_name = 'employee'
    
    success_url = reverse_lazy('hrms:employee_all') 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            print('*********************************')
            print(self.kwargs['pk'])
            queryset = Employee.objects.get(id=self.kwargs['pk'])

hrms/templates/hrms/footer.html
<footer class="footer">
          
</footer>

hrms/templates/hrms/layout.html
{% load static %}
{% load mathfilters %}

<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>{% block title  %}{% endblock title %}</title>
  <!-- plugins:css -->
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/mdi/css/materialdesignicons.min.css' %} ">
  <link rel="stylesheet" href="{% static 'hrms/vendors/iconfonts/font-awesome/css/font-awesome.css' %} ">
 
  
  <link rel="stylesheet" href="{% static 'hrms/css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'hrms/css/style.css' %}">
  <link rel="stylesheet" href="{% static 'hrms/css/toastr.min.css' %}">
  <link rel="shortcut icon" href="{% static 'hrms/images/favicon.png' %}" />
</head>
  
<body>
  <div class="container-scroller">
    {% include "hrms/nav.html" %}
    <div class="container-fluid page-body-wrapper">
      {% include 'hrms/sidebar.html' %}
        {% block content %} {% endblock content %}
        {% include 'hrms/footer.html' %}
    </div>
  </div>
  <!-- plugins:js -->
  
  <script src="{% static 'hrms/vendors/js/vendor.bundle.base.js' %}"></script>
  <script src="{% static 'hrms/vendors/js/vendor.bundle.addons.js' %}"></script>
  <script src="{% static 'hrms/js/toastr.min.js' %}"></script>
  <script src="{% static 'hrms/js/sweetalert2@8.js' %}"></script>
  <script src="{% static 'hrms/js/pay.js' %}"></script>
  
  <script src="{% static 'hrms/js/custom.js' %}"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script   src="https://code.jquery.com/jquery-3.1.1.min.js"   integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="   crossorigin="anonymous"></script>

  <script type="text/javascript">
  $('.no_of_months').click(function(){

    no_of_months = $("#no_of_months option").filter(":selected").val();
    console.log(no_of_months)
  $.ajax(
  {
      type:"GET",
      url: "/total_expense",
      data:{
          no_of_months: no_of_months
      },
      success: function( data ) 
      {
        document.getElementById('price_sum').innerHTML =data['price__sum']
         console.log(data);
      }
   })
});
</script>


  {% block noty %}
  {% endblock noty %}
</body>

</html>

hrms/templates/hrms/nav.html
    {% load static %}
    <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <p class="display-4 mt-3 text-success">Concrete Pumps</p>
        <a class="navbar-brand brand-logo-mini" href="{% url 'hrms:dashboard' %}">
        
          <img src="{{user.thumb.url}}" />
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
        
        <ul class="navbar-nav navbar-nav-right">          
          <li class="nav-item dropdown d-none d-xl-inline-block">
          
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text"> Hello, {{user.username | upper }} ! </span>
              <img class="img-xs rounded-circle" src=" {{user.thumb.url}} " alt="Profile image">
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              {% comment %} <a class="dropdown-item p-0">
                <div class="d-flex border-bottom">
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-bookmark-plus-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                    <i class="mdi mdi-account-outline mr-0 text-gray"></i>
                  </div>
                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                    <i class="mdi mdi-alarm-check mr-0 text-gray"></i>
                  </div>
                </div>
              </a> {% endcomment %}
              {% comment %} <a class="dropdown-item mt-2">
                Manage Accounts
              </a>
              <a class="dropdown-item">
                Change Password
              </a>
              <a class="dropdown-item">
                Check Inbox
              </a> {% endcomment %}
              <a class="dropdown-item" href='{% url 'hrms:logout' %}'>
                Log Out
              </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>

hrms/templates/hrms/sidebar.html
<nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <img src="{{user.thumb.url}}">
                </div>
                <div class="text-wrapper">
                  <p class="profile-name">{{user.username | upper}} </p>
                  
                  {% if user.role == 1 %}
                  <div>
                    <small class="designation text-muted">Administrator</small>
                    <span class="status-indicator online"></span>
                  </div>
                  
                  {% endif %}

                  {% if user.role == 2 %}
                  <div>
                    <small class="designation text-muted">Employee</small>
                    <span class="status-indicator online"></span>
                  </div>
                  
                  {% endif %}

                </div>
              </div>
              
              {% if user.role == 1 %}
              <a href="{% url 'hrms:employee_new' %}" class="btn btn-success btn-block">New Staff
                <i class="mdi mdi-plus"></i>
              </a>
              
              {% endif %}

              {% if user.role == 2 %}
              {% if present|length > 0 %}
              <p>{{present.counter}}</p>
              <a  class="btn btn-success btn-block">Already Signed in
                <i class="mdi mdi-plus"></i>
              </a>
              {% else %}
              <a onclick="checkin('{{user.id}}')" class="btn btn-success btn-block">Check In 
                <i class="mdi mdi-plus"></i>
              </a>
              {% endif %}
              {% endif %}
            </div>
          </li>
          
          {% if user.role == 1 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:dashboard' %}">
              <i class="fa  fa-dashboard"></i>
              <span class="menu-title">&emsp;Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:employee_all' %}" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-list text-dark"></i>
              <span class="menu-title">&emsp;Employee</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:cust_all' %}" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-list text-dark"></i>
              <span class="menu-title">&emsp;Customer</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:attendance_new' %}">
              <i class="fa fa-calendar"></i>
              <span class="menu-title">&emsp;Attendance</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:leave_new' %}">
              <i class="fa fa-sign-out "></i>
              <span class="menu-title">&emsp;Leave</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="fa fa-folder "></i>
              <span class="menu-title">&emsp;Department</span>
              <i class="menu-arrow"></i>
            </a>
              <a class="nav-link" href="{% url 'hrms:dept_new' %}"><i class="fa fa-plus"></i>&emsp;New Department</a>
              
            <hr>

            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">
              {% for dept in depts  %}
                <li class="nav-item">
                  <a class="nav-link" href="{{dept.get_absolute_url}}">{{dept.name}}</a>
                </li>
              {% endfor %}
              </ul>
            </div>
          </li>


          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:recruitmentall' %}">
              <i class="fa fa-database"></i>
              <span class="menu-title">&emsp;Recruitment</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:payroll' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Payroll</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:expenses_all' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Expenses</span>
            </a>
          </li>

          {% comment %} <li class="nav-item">

          <li class="nav-item">
            <a class="nav-link" href="pages/icons/font-awesome.html">
              <i class="fa  fa-gears"></i>
              <span class="menu-title">&emsp;Settings</span>
            </a>
          </li> {% endcomment %}
          
          {% endif %}
          {% if user.role == 2 %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:work_arrangeement_view' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;My Work Arrangements</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:employee_salary_view' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;My Salary</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:individual_all_employee_coupon_pdf' %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;My Coupons</span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:chat_employer'%}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;Chat </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'hrms:employee_individual_update' pk=employee.pk %}">
              <i class="fa fa-usd"></i>
              <span class="menu-title">&emsp;My Profile</span>
            </a>
          </li>
          {% endif %}

        </ul>
      </nav>